AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-pywebcv2

  Sample SAM Template for sam-pywebcv2

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  PywebFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pywebcv2/
      Handler: web.handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-1:975050204353:layer:pywebcv2:3
      
     
  # TextProcessorLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: TextProcessorLayer
  #     Description: Text processor dependencies
  #     ContentUri: 'layers/text-processor-layer/'
  #     CompatibleRuntimes:
  #       - nodejs18.x
  #   Metadata:
  #     BuildMethod: nodejs18.x          

  
      Events:
        Pyweb:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
    
      Events:
        pyweb:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PywebApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pyweb/"
  PywebFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt PywebFunction.Arn
  PywebFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt PywebFunctionRole.Arn
